export const AUDIT_LOG_ACTIONS = {
  authLogin: 'auth.login',
  authLogout: 'auth.logout',
  authLogoutAll: 'auth.logout_all',
  authPasswordChanged: 'auth.password_changed',
  authRefresh: 'auth.refresh',
  authRegister: 'auth.register',
  authVerificationCompleted: 'auth.verification_completed',
  fileAttached: 'file.attached',
  fileBulkDeleted: 'file.bulk_deleted',
  fileDeleted: 'file.deleted',
  fileUploadCompleted: 'file.upload_completed',
  fileUploadUrlCreated: 'file.upload_url_created',
  oauthLogin: 'oauth.login',
  oauthUnlinked: 'oauth.unlinked',
  userAdminBulkDeleted: 'user.admin_bulk_deleted',
  userAdminCreated: 'user.admin_created',
  userAdminDeleted: 'user.admin_deleted',
  userAdminPasswordReset: 'user.admin_password_reset',
  userAdminUpdated: 'user.admin_updated',
  userDeleted: 'user.deleted',
  userForceLogout: 'user.force_logout',
  userUpdated: 'user.updated',
  onboardingSaved: 'onboarding.saved',
  fieldChoiceSaved: 'field.choice_saved',
  shortSeriesCreated: 'short_series.created',
  shortGenerationRequested: 'short_generation.requested',
  shortLiked: 'short.liked',
  shortUnliked: 'short.unliked',
  shortCommentCreated: 'short_comment.created',
  shortCommentDeleted: 'short_comment.deleted',
  textSummaryCreated: 'text_summary.created',
  expressionDragged: 'expression.dragged',
} as const;

export type AuditLogAction = (typeof AUDIT_LOG_ACTIONS)[keyof typeof AUDIT_LOG_ACTIONS];
