import { RBAC } from './rbac.catalog';
import { RBAC_ROLES, type RbacGrant, type RbacRole } from './rbac.definitions';
import { grantEntity, inheritEntity } from './rbac.helpers';

export const RBAC_GRANTS: Record<RbacRole, readonly RbacGrant[]> = {
  [RBAC_ROLES.admin]: [
    inheritEntity('user'),
    RBAC.auditLog.list,
    RBAC.user.list,
    RBAC.user.create,
    RBAC.user.read,
    RBAC.user.update,
    RBAC.user.delete,
    RBAC.user.resetPassword,
    RBAC.user.forceLogout,
    RBAC.user.readOAuth,
    RBAC.user.unlinkOAuth,
    RBAC.file.adminCreateUpload,
    RBAC.file.adminComplete,
    RBAC.file.adminList,
    RBAC.file.adminDelete,
    RBAC.system.readMetrics,
  ],
  [RBAC_ROLES.user]: [
    grantEntity('auth'),
    grantEntity('file'),
    RBAC.user.deleteSelf,
    RBAC.user.readSelf,
    RBAC.user.unlinkOAuthSelf,
    RBAC.user.updateSelf,
    RBAC.onboarding.save,
    RBAC.onboarding.read,
    RBAC.field.generateTerms,
    RBAC.field.saveChoice,
    RBAC.short.createSeries,
    RBAC.short.requestGenerate,
    RBAC.short.listGenerations,
    RBAC.short.listSeries,
    RBAC.short.readSeries,
    RBAC.short.suggest,
    RBAC.short.checkDuplicate,
    RBAC.short.like,
    RBAC.short.createComment,
    RBAC.short.listComments,
    RBAC.short.deleteComment,
    RBAC.textSummary.create,
    RBAC.learning.read,
    RBAC.search.read,
  ],
};
