import { OpenAPIObject } from '@nestjs/swagger';
import { wrapSuccessResponses } from './openapi-envelope.patches';
import { addProblemDetailsResponses } from './openapi-problem-details.patches';
import {
  addCommonSchemas,
  promoteDefaultSuccessResponses,
  removeLegacyResponseSchemas,
  removePublicSecurity,
  removeRedundantFormatPatterns,
  removeZodOutputSchemaSuffix,
} from './openapi-schema.patches';
import {
  addTagGroups,
  dedupeOperationTags,
  removeAutoGeneratedControllerTags,
} from './openapi-tag.patches';

export function applyOpenApiDocumentPatches(document: OpenAPIObject) {
  const exampleTimestamp = new Date().toISOString();

  dedupeOperationTags(document);
  removeAutoGeneratedControllerTags(document);
  addTagGroups(document);
  removePublicSecurity(document);
  addCommonSchemas(document, exampleTimestamp);
  removeZodOutputSchemaSuffix(document);
  removeRedundantFormatPatterns(document);
  removeLegacyResponseSchemas(document);
  promoteDefaultSuccessResponses(document);
  wrapSuccessResponses(document, exampleTimestamp);
  addProblemDetailsResponses(document);
}
