import { OpenAPIObject } from '@nestjs/swagger';
import {
  buildOpenApiTagGroups,
  getNestJsAutoControllerTags,
  getOpenApiTagMeta,
} from '@/common/openapi/openapi-tag-registry';
import { OPENAPI_METHODS } from './openapi-methods';

type OpenApiDocumentWithTagGroups = OpenAPIObject & {
  'x-tagGroups'?: Array<{
    name: string;
    tags: string[];
  }>;
};

export function dedupeOperationTags(document: OpenAPIObject) {
  for (const pathItem of Object.values(document.paths)) {
    for (const method of OPENAPI_METHODS) {
      const operation = pathItem?.[method];

      if (!operation?.tags) {
        continue;
      }

      operation.tags = [...new Set(operation.tags)];
    }
  }
}

export function removeAutoGeneratedControllerTags(document: OpenAPIObject) {
  const autoControllerTags = getNestJsAutoControllerTags();

  for (const pathItem of Object.values(document.paths)) {
    for (const method of OPENAPI_METHODS) {
      const operation = pathItem?.[method];

      if (!operation?.tags) {
        continue;
      }

      operation.tags = operation.tags.filter((tag) => !autoControllerTags.has(tag));
    }
  }

  if (!document.tags) {
    return;
  }

  document.tags = document.tags.filter((tag) => !autoControllerTags.has(tag.name));
}

export function addTagGroups(document: OpenAPIObject) {
  const documentWithTagGroups = document as OpenApiDocumentWithTagGroups;
  const usedTags = collectUsedTags(document);

  documentWithTagGroups['x-tagGroups'] = buildOpenApiTagGroups(usedTags);

  document.tags ??= [];

  for (const tagName of usedTags) {
    const existingTag = document.tags.find((tag) => tag.name === tagName);
    const description = getOpenApiTagMeta(tagName)?.description;

    if (existingTag) {
      if (description) {
        existingTag.description ??= description;
      }
      continue;
    }

    document.tags.push({
      name: tagName,
      description,
    });
  }
}

function collectUsedTags(document: OpenAPIObject) {
  const usedTags = new Set<string>();

  for (const pathItem of Object.values(document.paths)) {
    for (const method of OPENAPI_METHODS) {
      const operation = pathItem?.[method];

      if (!operation?.tags) {
        continue;
      }

      for (const tag of operation.tags) {
        usedTags.add(tag);
      }
    }
  }

  return usedTags;
}
